# Generated by Django 4.2.27 on 2025-12-07 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the ingredient (e.g., Tomato, Rice)', max_length=100)),
                ('units_available', models.DecimalField(decimal_places=2, default=0.0, help_text='Quantity available in stock', max_digits=10)),
                ('unit_type', models.CharField(default='pieces', help_text='Unit of measurement (e.g., kg, pieces, liters)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ingredients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(help_text='Name of the meal (e.g., Chicken Curry, Pasta)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Full description of how to prepare the meal', null=True)),
                ('web_link', models.URLField(blank=True, help_text='Optional URL to external recipe website', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recipes',
                'ordering': ['meal_name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(help_text="Quantity needed (e.g., '2 pieces', '500g', '1 cup')", max_length=100)),
                ('ingredient', models.ForeignKey(help_text='Reference to the ingredient', on_delete=django.db.models.deletion.CASCADE, to='entities.ingredient')),
                ('recipe', models.ForeignKey(help_text='Reference to the recipe', on_delete=django.db.models.deletion.CASCADE, to='entities.recipe')),
            ],
            options={
                'db_table': 'recipe_ingredients',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Ingredients required for this recipe', related_name='recipes', through='entities.RecipeIngredient', to='entities.ingredient'),
        ),
        migrations.CreateModel(
            name='MealSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(help_text='Name of the meal being scheduled', max_length=200)),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], help_text='Day of the week for this meal', max_length=10)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], help_text='Type of meal (breakfast, lunch, or dinner)', max_length=10)),
                ('scheduled_date', models.DateField(blank=True, help_text='Optional: specific date for the meal', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for this scheduled meal', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(blank=True, help_text='Optional reference to a recipe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_meals', to='entities.recipe')),
            ],
            options={
                'db_table': 'meal_schedules',
                'ordering': ['day_of_week', 'meal_type'],
            },
        ),
    ]
